#!/bin/sh

# Copyright (c) 1992, 1994, 1995, 1996 Xerox Corporation.  All rights reserved.
# Portions of this code were written by Stephen White, aka ghond.
# Use and copying of this software and preparation of derivative works based
# upon this software are permitted.  Any distribution of this software or
# derivative works must comply with all applicable United States export
# control laws.  This software is made available AS IS, and Xerox Corporation
# makes no warranty about the software, its performance or its conformity to
# any specification.  Any person obtaining a copy of this software is requested
# to send their name and post office or electronic mail address to:
#   Pavel Curtis
#   Xerox PARC
#   3333 Coyote Hill Rd.
#   Palo Alto, CA 94304
#   Pavel@Xerox.Com

if [ $# -lt 1 -o $# -gt 2 ]; then
	echo 'Usage: restart dbase-prefix [port]'
	exit 1
fi

if [ ! -r $1.db ]; then
	echo "Unknown database: $1.db"
	exit 1
fi

if [ -r $1.db.new ]; then
	echo "Shuffling databases..."
	mv -v $1.db $1.db.old
	mv -v $1.db.new $1.db
	rm -fv $1.db.old.gz
	echo "$1.db.old will be gzipping in the background."
	gzip $1.db.old &
fi

if [ -f $1.log ]; then
	echo "$1.log moved temporarily to $1.log.old"
	cat $1.log >> $1.log.old
	rm $1.log
fi

echo `date`: RESTARTED >> $1.log
echo "Restarting with $1.db, dumping to $1.db.new and logging to $1.log"

# Make sure we find moo, no matter how this script is called.
MOO="$(dirname "$0")/moo"

nohup "$MOO" $1.db $1.db.new $2 >> $1.log 2>&1 &

if [ -f $1.log.old ]; then
	echo "Now gzipping $1.log.old"
	gzip $1.log.old
	mv -v $1.log.old.gz $1.log.`date | awk '{ print $6 $2 $3 }'`.gz
fi

###############################################################################
# $Log: restart,v $
# Revision 1.4  2009/03/28 21:41:33  blacklite
# this is the version in the moo dir that we use -- updated with more verbosity and more clearly marked backups.
#
# Revision 2.1  1996/02/08  07:25:45  pavel
# Updated copyright notice for 1996.  Release 1.8.0beta1.
#
# Revision 2.0  1995/11/30  05:14:43  pavel
# New baseline version, corresponding to release 1.8.0alpha1.
#
# Revision 1.2  1994/05/26  16:43:13  pavel
# Fixed up copyright, RCS info; removed debugging switch.
#
# Revision 1.1  1994/05/26  16:41:32  pavel
# Initial revision
###############################################################################
